// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnbiID4tDnR4oprPUgo4cNyogX2BkGB-Y',
    appId: '1:616371063592:web:2c7a6898235da28f679e1d',
    messagingSenderId: '616371063592',
    projectId: 'nmhas-guideline-platform',
    authDomain: 'nmhas-guideline-platform.firebaseapp.com',
    storageBucket: 'nmhas-guideline-platform.firebasestorage.app',
    measurementId: 'G-Q5GM68RTSQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiwjGVJVKM3SZIg_aMSsdz3n_exJR2U_E',
    appId: '1:616371063592:android:0b9a611ac288a412679e1d',
    messagingSenderId: '616371063592',
    projectId: 'nmhas-guideline-platform',
    storageBucket: 'nmhas-guideline-platform.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvbETzMLqGd6erKy3S7VU0HddPrDwSmY4',
    appId: '1:616371063592:ios:99977c85f99d8253679e1d',
    messagingSenderId: '616371063592',
    projectId: 'nmhas-guideline-platform',
    storageBucket: 'nmhas-guideline-platform.firebasestorage.app',
    iosBundleId: 'com.nmhas.nmhasApp',
  );
}
